// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5sgKlyPWdb5VB9eEZbzAvmdIZtBr5fs',
    appId: '1:95757139210:web:386498694ada631d328ef3',
    messagingSenderId: '95757139210',
    projectId: 'tubesppb-5d0b8',
    authDomain: 'tubesppb-5d0b8.firebaseapp.com',
    storageBucket: 'tubesppb-5d0b8.appspot.com',
    measurementId: 'G-TVVZXZXS9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA516wlpeUIvLWYlOObw4ZhXj7Cxcp1zF8',
    appId: '1:95757139210:android:d4cd82cc7d0e2501328ef3',
    messagingSenderId: '95757139210',
    projectId: 'tubesppb-5d0b8',
    storageBucket: 'tubesppb-5d0b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSvO_8mGGVq7exevqLLZAtOcADUB2ESCU',
    appId: '1:95757139210:ios:f40c29bf010b5eec328ef3',
    messagingSenderId: '95757139210',
    projectId: 'tubesppb-5d0b8',
    storageBucket: 'tubesppb-5d0b8.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSvO_8mGGVq7exevqLLZAtOcADUB2ESCU',
    appId: '1:95757139210:ios:f40c29bf010b5eec328ef3',
    messagingSenderId: '95757139210',
    projectId: 'tubesppb-5d0b8',
    storageBucket: 'tubesppb-5d0b8.appspot.com',
    iosBundleId: 'com.example.tubes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ5sgKlyPWdb5VB9eEZbzAvmdIZtBr5fs',
    appId: '1:95757139210:web:883103169a1afa7d328ef3',
    messagingSenderId: '95757139210',
    projectId: 'tubesppb-5d0b8',
    authDomain: 'tubesppb-5d0b8.firebaseapp.com',
    storageBucket: 'tubesppb-5d0b8.appspot.com',
    measurementId: 'G-6KGX0E1D3L',
  );
}
